# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
r: devel
cache: packages
warnings_are_errors: false
sudo: required
r_check_args: "--as-cran"

env:
 global:
   - CRAN: http://cran.rstudio.com


r_packages:
- devtools
- ade4


before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable --yes
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install --yes libudunits2-dev libproj-dev libgeos-dev libgdal-dev gsl-bin libgsl2 libgsl-dev
  - Rscript -e 'update.packages(ask = FALSE)'

notifications:
  email:
  on_success: change
  on_failure: change

# Sample .travis.yml for R projects




